apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
  namespace: demo
spec:
  instances: 3
  imageName: ghcr.io/carverauto/serviceradar-cnpg:16.6.0-sr2@sha256:aa49dec4057652983bfbb134d561c5461093da80a0b256804a8e5a79481f3b88
  imagePullSecrets:
    - name: ghcr-io-cred

  storage:
    size: 100Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: spire
      owner: spire
      secret:
        name: spire-db-credentials
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS timescaledb;
        - CREATE EXTENSION IF NOT EXISTS age;

  postgresql:
    shared_preload_libraries:
      - timescaledb
      - age

  managed:
    roles:
      - name: spire
        ensure: present
        login: true
        passwordSecret:
          name: spire-db-credentials

  monitoring:
    enablePodMonitor: true
