apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: serviceradar-rperf-checker
spec:
  spiffeIDTemplate: spiffe://carverauto.dev/ns/$(SERVICERADAR_NAMESPACE)/sa/serviceradar-rperf-checker
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: $(SERVICERADAR_NAMESPACE)
  podSelector:
    matchLabels:
      app: serviceradar-rperf-client
