apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: serviceradar
  namespace: promoter-system
spec:
  github:
    owner: carverauto
    name: serviceradar
  scmProviderRef:
    name: github-carverauto
