apiVersion: promoter.argoproj.io/v1alpha1
kind: ScmProvider
metadata:
  name: github-carverauto
  namespace: promoter-system
spec:
  secretRef:
    name: github-token
  github:
    domain: github.com
# Secret format for PAT:
# kubectl create secret generic github-token \
#   --namespace promoter-system \
#   --from-literal=token=ghp_xxxxxxxxxxxx
