apiVersion: v1
kind: ConfigMap
metadata:
  name: sr-testing-nats-config
data:
  nats-server.conf: |
    port: 4222

    http: 8222

    jetstream {
      store_dir: "/data/jetstream"
    }

    tls {
      ca_file: "/etc/nats/certs/ca.crt"
      cert_file: "/etc/nats/certs/server.crt"
      key_file: "/etc/nats/certs/server.key"
      # Require client certificates; tests should use the client cert from sr-testing-nats-tls.
      verify: true
    }
