apiVersion: v1
kind: Service
metadata:
  name: sr-testing-nats-ext
  labels:
    app: sr-testing-nats
  annotations:
    metallb.universe.tf/address-pool: k3s-pool
    metallb.universe.tf/ip-addr-pool: k3s-pool
    metallb.universe.tf/allow-shared-ip: serviceradar-public
    external-dns.alpha.kubernetes.io/hostname: sr-testing-nats.serviceradar.cloud.
spec:
  type: LoadBalancer
  selector:
    app: sr-testing-nats
  ports:
    - name: client
      port: 4222
      targetPort: client
