[package]
name = "srql"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
async-trait = "0.1.89"
axum = { version = "0.7.5", features = ["macros"] }
base64 = "0.22.1"
chrono = { version = "0.4.38", features = ["serde"] }
diesel = { version = "2.2.2", default-features = false, features = ["postgres", "chrono", "serde_json", "32-column-tables"] }
diesel-async = { version = "0.7.1", features = ["postgres", "tokio", "bb8"] }
envy = "0.4.2"
http = "1.1.0"
kvutil = { path = "../kvutil" }
once_cell = "1.20.2"
parking_lot = "0.12.3"
pq-sys = { version = "0.7.5", features = ["bundled"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_with = "3.11.0"
thiserror = "1.0.69"
tokio = { version = "1.41.0", features = ["full"] }
tower = "0.5.1"
tower-http = { version = "0.6.1", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
uuid = { version = "1.11.0", features = ["serde", "v4"] }
bb8 = "0.8"
tokio-postgres = "0.7"
tokio-postgres-rustls = "0.12"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rustls-pemfile = "2.2"

[dev-dependencies]
pretty_assertions = "1.4.1"
serial_test = "3.2"
testcontainers = "0.25"
