apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-test-credentials.yaml
  - cnpg-test-admin-credentials.yaml
  - cnpg-cluster.yaml
  - services.yaml
